# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build notebooks

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        $CONDA/bin/pip install -r requirements.txt

    - name: Build Markdown files
      run: |
        make markdown JUPYTER=$CONDA/bin/jupyter PYTHON3=$CONDA/bin/python3

    - name: Commit and push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "build notebooks for ${{ github.sha }}" || :
        git push
